package io.dohrm.adventOfCode2022

object D2 {
  enum Result(val player: String, val value: Int):
    case Lose extends Result("X", 0)
    case Draw extends Result("Y", 3)
    case Win  extends Result("Z", 6)

  enum Choice(val opponent: String, val player: String, val value: Int):
    case Rock     extends Choice("A", "X", 1)
    case Paper    extends Choice("B", "Y", 2)
    case Scissors extends Choice("C", "Z", 3)

  private def result(opponent: Choice, player: Choice): Result = {
    (opponent, player) match
      case (a, b) if a == b => Result.Draw
      case (Choice.Rock, Choice.Paper) | (Choice.Paper, Choice.Scissors) | (Choice.Scissors, Choice.Rock) =>
        Result.Win
      case _ => Result.Lose
  }

  private def result(opponent: Choice, expected: Result): Choice =
    expected match
      case Result.Draw => opponent
      case Result.Lose =>
        opponent match
          case Choice.Rock     => Choice.Scissors
          case Choice.Paper    => Choice.Rock
          case Choice.Scissors => Choice.Paper
      case Result.Win =>
        opponent match
          case Choice.Rock     => Choice.Paper
          case Choice.Paper    => Choice.Scissors
          case Choice.Scissors => Choice.Rock

  private def part1(value: String): Int = {
    val s = value.split(' ').map(_.trim)
    if (s.length != 2) return 0
    (Choice.values.find(_.opponent == s(0)), Choice.values.find(_.player == s(1))) match
      case (Some(a), Some(b)) => result(a, b).value + b.value
      case _                  => 0
  }

  private def part2(value: String): Int = {
    val s = value.split(' ').map(_.trim)
    if (s.length != 2) return 0
    (Choice.values.find(_.opponent == s(0)), Result.values.find(_.player == s(1))) match
      case (Some(a), Some(b)) => result(a, b).value + b.value
      case _                  => 0
  }

  private def readAll(fn: String => Int, value: String): Int =
    value.split("\n").foldLeft(0)(_ + fn(_))

  // 15572

  def main(args: Array[String]): Unit =
    println(
      readAll(
        part2,
        """C Z
                |C X
                |B Z
                |A X
                |A Z
                |C Z
                |A Y
                |C Z
                |C Z
                |A X
                |C Y
                |A Z
                |B Z
                |C Z
                |C Z
                |B Z
                |C Z
                |B Z
                |C Z
                |A X
                |C Z
                |C Z
                |A X
                |C Z
                |B Z
                |B Z
                |C Z
                |C Z
                |B Z
                |A X
                |A X
                |C Z
                |C Z
                |A X
                |B Z
                |B Z
                |B Z
                |A X
                |A X
                |A X
                |B Z
                |C Z
                |C Z
                |C Z
                |B Z
                |C X
                |B Z
                |B Z
                |A X
                |C Z
                |C Z
                |B Z
                |A Y
                |A Z
                |C X
                |A X
                |C Z
                |C Z
                |B Z
                |C Z
                |C Z
                |C X
                |C Z
                |A X
                |B Z
                |B Z
                |C X
                |C Z
                |B Z
                |B Z
                |C Z
                |B Z
                |B Z
                |C Z
                |B Z
                |A Z
                |A X
                |C Z
                |B X
                |B Z
                |C Z
                |C Z
                |A Z
                |B Z
                |C Z
                |B Z
                |B Y
                |A Z
                |C Z
                |B Z
                |A X
                |A Y
                |C Z
                |B Z
                |B Z
                |A X
                |B Z
                |A Z
                |B Z
                |C Z
                |C Y
                |C Z
                |B Z
                |C Z
                |C Z
                |C Z
                |C X
                |B Z
                |B Z
                |B Z
                |B Z
                |A X
                |C Z
                |C Z
                |A X
                |C Z
                |B Z
                |B Z
                |C Z
                |C Z
                |C Z
                |A X
                |B Z
                |C Z
                |B Z
                |B Z
                |C X
                |A Z
                |B Z
                |C Z
                |A X
                |A X
                |A X
                |B Z
                |B Z
                |B Z
                |B Z
                |B Z
                |B Z
                |C Z
                |B X
                |C Z
                |C Z
                |B X
                |C Z
                |C Y
                |A X
                |C Z
                |A Z
                |A X
                |B Z
                |B Z
                |B Z
                |C Z
                |C X
                |A Z
                |C Z
                |C Y
                |A Y
                |A X
                |B Z
                |B X
                |C Z
                |A Z
                |C Z
                |B Z
                |B Z
                |A X
                |B Z
                |A X
                |C Y
                |B Z
                |B Y
                |A Z
                |B Z
                |A X
                |C Z
                |A X
                |C Z
                |B Z
                |A Z
                |B Z
                |A Y
                |C Z
                |C Z
                |C Z
                |B X
                |C Z
                |A X
                |B X
                |B Z
                |C Z
                |A X
                |B Z
                |B Z
                |A Z
                |B Y
                |B Z
                |B Z
                |C Z
                |C Z
                |B Z
                |C Z
                |B Z
                |A X
                |B X
                |A X
                |C Y
                |B Z
                |C Z
                |C Z
                |C Z
                |B Z
                |B Z
                |C Z
                |A X
                |A Y
                |C Z
                |B Z
                |B Z
                |C Z
                |B Y
                |C Z
                |B Z
                |C Z
                |B Z
                |B Z
                |C X
                |B Z
                |A Z
                |A X
                |A X
                |C Z
                |B Z
                |C Z
                |C Z
                |C Z
                |B Z
                |A Y
                |C Z
                |C Z
                |C Z
                |B Z
                |C Z
                |B Z
                |A X
                |C Z
                |B X
                |C Z
                |A X
                |B X
                |A Z
                |B Z
                |B X
                |A X
                |C Z
                |A Y
                |A Y
                |C X
                |C Z
                |C Z
                |A X
                |A Y
                |B Z
                |A Z
                |B Z
                |A X
                |C Z
                |B X
                |B Z
                |B Z
                |B Z
                |B Z
                |C Y
                |B Z
                |B Z
                |B Z
                |A Z
                |A Y
                |C Z
                |C Z
                |B Z
                |A Z
                |A X
                |A Y
                |C Z
                |B X
                |C Z
                |A X
                |A Z
                |B Z
                |A X
                |A X
                |C X
                |A X
                |A X
                |A Z
                |C Z
                |B Z
                |C Z
                |C Z
                |B Z
                |B Z
                |A Y
                |B Z
                |B Z
                |C Z
                |B Z
                |A Y
                |A X
                |B Z
                |C Z
                |B Z
                |A X
                |C Z
                |C Z
                |C Z
                |B Z
                |A Z
                |C Z
                |C Z
                |B Z
                |C X
                |B Z
                |B Z
                |B Z
                |A Y
                |A X
                |B Z
                |C Z
                |C Z
                |A Z
                |B Y
                |C Z
                |B Z
                |B Z
                |B Z
                |A X
                |A X
                |C Z
                |C Z
                |A X
                |C Z
                |B Z
                |A X
                |B Z
                |A X
                |B Z
                |B Z
                |A X
                |A X
                |C Z
                |A Y
                |A Z
                |B Y
                |C Z
                |C Z
                |B Y
                |A Z
                |C Z
                |B Z
                |C Z
                |C Z
                |B Z
                |C Z
                |A Y
                |C Z
                |A X
                |B X
                |C Z
                |A Y
                |B Z
                |B Z
                |C Z
                |B Z
                |A X
                |B Z
                |B Z
                |B Z
                |B Z
                |B Z
                |A Z
                |B Z
                |B Y
                |C Z
                |B Z
                |C Z
                |C X
                |B Z
                |B Z
                |B Z
                |B Z
                |A X
                |B Z
                |B Z
                |C Z
                |B Z
                |A X
                |A X
                |A Z
                |C Z
                |C Z
                |A X
                |A X
                |C Z
                |C Z
                |C Z
                |A Y
                |C Z
                |B Z
                |C Z
                |C Z
                |A Y
                |C Z
                |B Z
                |C X
                |A X
                |C Z
                |C Z
                |C Z
                |C Z
                |A X
                |C Z
                |C Z
                |A Y
                |C Z
                |C X
                |A X
                |C Z
                |B Z
                |C Z
                |A Z
                |B Z
                |B X
                |A Z
                |C Z
                |C Z
                |A X
                |C X
                |B Z
                |A Y
                |C Z
                |A X
                |B Z
                |C Z
                |A X
                |B Z
                |A X
                |C Z
                |C Y
                |B Z
                |A Y
                |B Z
                |B Z
                |B Z
                |B Z
                |A X
                |B Z
                |B Y
                |C Z
                |C Z
                |B Z
                |B Z
                |C Z
                |B Y
                |B Z
                |B Z
                |B X
                |B Z
                |C Z
                |B Z
                |A Y
                |A X
                |A X
                |C Z
                |C X
                |C Z
                |B Z
                |A Z
                |C Z
                |C Z
                |B Z
                |A Y
                |C Y
                |A X
                |A X
                |A X
                |B Z
                |A X
                |B Z
                |B Z
                |A Y
                |B Y
                |C Z
                |B Z
                |B Z
                |C Z
                |A X
                |A X
                |C Z
                |A Z
                |B Z
                |B X
                |B Z
                |B Z
                |A Y
                |C Z
                |B Z
                |A X
                |C X
                |C Z
                |C Z
                |B Z
                |A Z
                |C Z
                |C Z
                |C Z
                |C Z
                |C Z
                |C Y
                |C Z
                |B Z
                |B X
                |C Z
                |B Z
                |B Z
                |B Z
                |B Z
                |C Z
                |B Z
                |C X
                |C Z
                |B X
                |C Z
                |A Y
                |C Z
                |B Z
                |B Z
                |B Y
                |C Z
                |A X
                |B Z
                |C Z
                |C Y
                |A Y
                |A X
                |C Z
                |B Z
                |C Z
                |B Z
                |A X
                |A Y
                |A Y
                |B Y
                |C Z
                |C Z
                |C Z
                |B Z
                |C Z
                |A X
                |B Z
                |B X
                |B Z
                |C Z
                |C Z
                |B Z
                |B Z
                |B Z
                |B Z
                |A X
                |A Z
                |A Y
                |B Z
                |B X
                |B Z
                |C Y
                |B Y
                |B Z
                |B Z
                |B Z
                |C Y
                |C Z
                |B Z
                |A X
                |A X
                |A X
                |C Z
                |A Y
                |B Z
                |B Z
                |B Z
                |B Z
                |A X
                |B Z
                |B Z
                |C Z
                |B Z
                |A X
                |A X
                |A X
                |C Z
                |C Z
                |B Z
                |C Z
                |C Z
                |C X
                |B Z
                |C Z
                |C Z
                |B Z
                |A Y
                |B Z
                |B Z
                |C Z
                |C X
                |C Y
                |A X
                |C Z
                |A X
                |C Z
                |C Z
                |C Z
                |B Z
                |B Z
                |A Y
                |B Z
                |B Z
                |C Z
                |C X
                |C Z
                |B Z
                |B Z
                |B Z
                |C X
                |B Y
                |B X
                |A Z
                |C Z
                |B Z
                |A Z
                |B Y
                |B Z
                |A X
                |B Z
                |B Y
                |B Y
                |B Z
                |C Z
                |A X
                |C Z
                |B Z
                |C Z
                |C Z
                |A X
                |C Y
                |A Z
                |B Z
                |C Z
                |C Z
                |A X
                |B Y
                |C Z
                |C Z
                |A Z
                |C Z
                |B Z
                |B Z
                |C Z
                |B Z
                |A X
                |B Z
                |A Y
                |B Z
                |C Z
                |B Z
                |C Z
                |B Z
                |A Y
                |A X
                |A Y
                |C X
                |C Z
                |A X
                |C Z
                |A Z
                |C Z
                |C Z
                |A Z
                |C Z
                |A Z
                |B Z
                |C Z
                |B Z
                |A Z
                |B Z
                |B Z
                |A X
                |A Y
                |A X
                |C X
                |B Z
                |C Z
                |B Z
                |A X
                |C Z
                |B Z
                |A X
                |C Z
                |A X
                |C Y
                |A Y
                |C Z
                |C X
                |B Z
                |B Z
                |A X
                |C Z
                |B Y
                |C Z
                |A Y
                |B X
                |C Z
                |A X
                |B Z
                |C Z
                |C Z
                |C Z
                |B Z
                |B Z
                |A Z
                |C Z
                |A Y
                |B Z
                |B Z
                |A Y
                |B Z
                |B Z
                |B Z
                |C Z
                |B Z
                |C Z
                |A X
                |B Z
                |B Z
                |C Y
                |C Z
                |A X
                |C Z
                |C Z
                |C Z
                |C Y
                |C Z
                |A Z
                |B Z
                |B Z
                |C Z
                |B X
                |B Z
                |B Z
                |A Z
                |A X
                |C Z
                |C X
                |C Z
                |A Y
                |B Z
                |C Z
                |B Z
                |C Z
                |C Z
                |C X
                |B Z
                |B X
                |A Z
                |B Z
                |B Y
                |C Z
                |C X
                |C Z
                |A Z
                |C Z
                |B Z
                |C Z
                |C Z
                |C Y
                |C X
                |C Y
                |A Z
                |C X
                |A X
                |C Y
                |B Y
                |A Z
                |B Y
                |C Z
                |C Z
                |C Z
                |B Z
                |C Z
                |A X
                |C Z
                |A X
                |B Z
                |C Z
                |C Z
                |A Y
                |B Z
                |C Z
                |C Z
                |C Z
                |A X
                |B Z
                |C Z
                |B Z
                |C Z
                |B Z
                |B X
                |B Z
                |C Z
                |B Z
                |B Z
                |A Z
                |A Y
                |B Z
                |B Z
                |B Z
                |C Z
                |B Z
                |B Z
                |B Z
                |A Y
                |C Z
                |A X
                |C Z
                |A X
                |B X
                |C Z
                |B Z
                |B Z
                |B Z
                |C Z
                |C Z
                |C X
                |B Z
                |B Z
                |C Z
                |B Z
                |C X
                |A X
                |B Y
                |A X
                |A Z
                |B Z
                |C Z
                |B Z
                |C X
                |B X
                |A Z
                |C Z
                |C Z
                |C Z
                |A Z
                |B X
                |C Z
                |B Z
                |A X
                |B Z
                |C Z
                |A X
                |B Z
                |C Z
                |C Z
                |B Z
                |C Z
                |C Z
                |B Z
                |C Z
                |A Z
                |C Z
                |A Y
                |B Z
                |B Z
                |B Z
                |C Z
                |A Y
                |C Z
                |B Z
                |C Z
                |B Z
                |A Z
                |C Y
                |C Z
                |C Z
                |A X
                |C Z
                |B Y
                |C Z
                |B Z
                |A Z
                |B Z
                |C Z
                |B Z
                |C Y
                |B Z
                |C Z
                |C Z
                |B Z
                |C Z
                |C Z
                |C Z
                |C Z
                |C Z
                |A X
                |A Z
                |A Y
                |A Y
                |C Z
                |A X
                |A Z
                |B Z
                |A Y
                |A X
                |B X
                |C Z
                |A Y
                |B Z
                |B Z
                |B Z
                |B Z
                |A Z
                |C Z
                |A X
                |B Y
                |C Y
                |C Y
                |C Z
                |C X
                |A X
                |A Y
                |B Z
                |A Z
                |A X
                |C Z
                |C Z
                |B Z
                |C Z
                |A Y
                |B Z
                |A X
                |C X
                |A X
                |B Z
                |C Z
                |C Z
                |A Y
                |A X
                |B Z
                |B Z
                |B Z
                |C Z
                |B Z
                |B Z
                |B Z
                |B X
                |C Y
                |C Z
                |C Z
                |B X
                |B Z
                |B Z
                |C Z
                |A X
                |B Z
                |B Z
                |B Z
                |A Z
                |B Z
                |B Z
                |B Z
                |C Z
                |A X
                |C Y
                |C Z
                |B Z
                |B Z
                |B X
                |A Z
                |A X
                |B Z
                |B Z
                |A Y
                |B Z
                |B Z
                |C Z
                |C Z
                |C X
                |B X
                |B Z
                |C Z
                |C Z
                |A X
                |C Z
                |A Z
                |C Z
                |C Y
                |A X
                |B Z
                |A X
                |A X
                |C Z
                |B X
                |C Z
                |A X
                |C Z
                |C Z
                |C Z
                |A Y
                |A X
                |C Z
                |A Z
                |C Z
                |B Z
                |C Y
                |C Z
                |B Z
                |A Y
                |C Z
                |B X
                |A X
                |B Z
                |C Z
                |A X
                |B X
                |B Y
                |B Z
                |B Z
                |A Y
                |B Z
                |B X
                |B Y
                |B Z
                |C Z
                |C Z
                |A Z
                |A X
                |C Z
                |A Z
                |C Z
                |A X
                |C Z
                |C Z
                |B Z
                |B Z
                |C Z
                |C X
                |C Z
                |A X
                |C Z
                |B Z
                |C Z
                |A X
                |A X
                |A X
                |C Z
                |C Z
                |A Z
                |C Z
                |B Z
                |A X
                |B Z
                |B X
                |C Z
                |B Z
                |C Z
                |B Z
                |B X
                |C Z
                |A Z
                |A Z
                |C Z
                |B Z
                |B Z
                |B Z
                |C Z
                |C X
                |B Z
                |A X
                |B Z
                |B Z
                |C Z
                |B Z
                |C Z
                |B Z
                |B X
                |C Z
                |C Z
                |A X
                |C Z
                |C Z
                |B Z
                |A X
                |C Y
                |B Z
                |C Z
                |A Y
                |B Z
                |C Z
                |A X
                |B Z
                |C Z
                |C X
                |A Z
                |C Z
                |C Y
                |B Z
                |B Z
                |A X
                |B Z
                |B Z
                |A Z
                |C Z
                |B Z
                |A X
                |A Z
                |B Z
                |B Z
                |C Z
                |C Z
                |A X
                |A Y
                |B Z
                |B Z
                |A Y
                |A X
                |C Z
                |A Y
                |A X
                |C Z
                |C Z
                |B Z
                |A X
                |C Z
                |A X
                |C Z
                |B X
                |C Z
                |B Z
                |C Y
                |B Z
                |C Y
                |C Z
                |B Z
                |B Z
                |A Y
                |C Z
                |C Y
                |A X
                |B Z
                |B Z
                |A X
                |B Z
                |B Z
                |B Z
                |A X
                |A Y
                |C Z
                |C Z
                |C X
                |B X
                |A X
                |A X
                |B Z
                |A X
                |B Z
                |B Z
                |B Z
                |B X
                |C Z
                |C Z
                |B Z
                |C Z
                |C Z
                |A X
                |B Z
                |C Z
                |C Z
                |C Z
                |C Z
                |B Z
                |C Z
                |C Z
                |B Z
                |B Z
                |A X
                |C Z
                |B Z
                |C Z
                |C Z
                |C Z
                |B Z
                |A X
                |C Z
                |A Y
                |B Z
                |C Z
                |C Z
                |C Z
                |A X
                |B Z
                |C Y
                |C Z
                |C X
                |B Z
                |B Z
                |B Z
                |A Z
                |C Y
                |B Z
                |B Z
                |B Z
                |C Z
                |C Y
                |A X
                |B Z
                |B Z
                |C Y
                |C Z
                |A X
                |A Z
                |C X
                |C X
                |A Z
                |B X
                |A X
                |C Z
                |C Z
                |B Z
                |C Z
                |B Y
                |C Z
                |C Z
                |B Z
                |B Z
                |A Z
                |B Z
                |B Z
                |A X
                |C Z
                |B X
                |B Y
                |B Z
                |C Y
                |C Z
                |B Z
                |A Z
                |C Z
                |C Z
                |B Z
                |C Z
                |A Z
                |C Z
                |A X
                |C Z
                |C Z
                |A Z
                |C X
                |C Z
                |A X
                |C Z
                |A X
                |C Z
                |A X
                |A Z
                |B Z
                |C Z
                |C Z
                |C Z
                |A X
                |A Z
                |C Z
                |C Y
                |A Y
                |C Y
                |C Z
                |B Y
                |A X
                |C Z
                |B Z
                |C Z
                |C Z
                |B Z
                |C Z
                |B Z
                |C X
                |C Z
                |B Z
                |C Z
                |A X
                |A X
                |A X
                |B Z
                |B Z
                |B Z
                |A X
                |A Z
                |B Z
                |C Z
                |C Z
                |A X
                |A Y
                |C Z
                |A X
                |C Z
                |A Y
                |A X
                |A Z
                |A Z
                |C Z
                |C Z
                |B Y
                |C Z
                |A X
                |B Z
                |A Z
                |B Z
                |C Z
                |A X
                |C X
                |B Z
                |B Z
                |C Z
                |C Z
                |A X
                |B Z
                |C Z
                |B Z
                |A X
                |B Z
                |C Y
                |A X
                |B Z
                |B Z
                |C Z
                |C Z
                |A X
                |B Z
                |B Z
                |C Z
                |B Z
                |C Z
                |A X
                |C Z
                |C Z
                |B Z
                |A X
                |C Z
                |B Z
                |B X
                |C Z
                |C Y
                |B X
                |A Z
                |A Z
                |C Z
                |A Y
                |B X
                |B Z
                |C Z
                |C Z
                |C Z
                |A Z
                |C Z
                |C Z
                |C Y
                |C Z
                |B Z
                |A Z
                |A Z
                |C X
                |C Z
                |B Y
                |C Z
                |C Z
                |C X
                |B Y
                |A X
                |C X
                |A Y
                |C Z
                |A Y
                |C Y
                |A X
                |B Z
                |C Z
                |B Z
                |A X
                |A X
                |C Z
                |B Z
                |A X
                |C Z
                |A Y
                |C X
                |B Z
                |C Z
                |C Z
                |A X
                |C Z
                |C Z
                |A X
                |C Y
                |A X
                |A X
                |C Z
                |B Z
                |A X
                |A X
                |C Z
                |A X
                |C Z
                |B Z
                |A Z
                |C Z
                |B X
                |C Z
                |C Z
                |B Z
                |A Y
                |A X
                |C Y
                |B Z
                |B Z
                |B Z
                |A X
                |A Z
                |C Z
                |C Z
                |C Z
                |A Z
                |B Z
                |C Z
                |A Z
                |B Z
                |C Z
                |A X
                |A X
                |B Z
                |A X
                |C Z
                |C Z
                |B Z
                |C X
                |B Z
                |A X
                |A X
                |C Z
                |C Z
                |B Z
                |A X
                |A Y
                |B Z
                |A X
                |C Z
                |C Z
                |A X
                |A Y
                |A X
                |C X
                |A Y
                |A X
                |B Z
                |C Y
                |B Z
                |C Z
                |C Z
                |B Z
                |C Z
                |C Z
                |C X
                |C Z
                |C X
                |B Z
                |B Z
                |C Z
                |B X
                |C Z
                |B Z
                |C Z
                |C Z
                |A Y
                |B X
                |A X
                |A Y
                |A X
                |B Z
                |C Z
                |C Z
                |A X
                |C Y
                |B Z
                |B Z
                |B Z
                |B Z
                |A X
                |C Z
                |A X
                |B Z
                |C Z
                |A Z
                |C X
                |B X
                |C Z
                |B Y
                |A Z
                |A Y
                |A X
                |C Z
                |B X
                |B Z
                |A Z
                |A X
                |A Z
                |C Z
                |B Z
                |C Z
                |A X
                |B Z
                |C Z
                |B Z
                |B Z
                |C Z
                |B X
                |B Z
                |A X
                |A X
                |A X
                |B Z
                |B Z
                |B Z
                |A X
                |C Z
                |C Y
                |B Z
                |B X
                |C Z
                |C Y
                |B Z
                |A X
                |C Z
                |C X
                |A X
                |B Z
                |C Z
                |A Z
                |B X
                |B Z
                |A X
                |C Z
                |B Z
                |B Z
                |B X
                |A Y
                |C Y
                |B Z
                |C Z
                |C X
                |C Z
                |B Z
                |C Z
                |A X
                |A X
                |B Z
                |A X
                |B Z
                |B Z
                |C Z
                |C Z
                |A X
                |B Z
                |C Y
                |B Z
                |C Z
                |C Z
                |C Z
                |B Z
                |B X
                |C Z
                |C Z
                |C Z
                |B Z
                |B Z
                |C Z
                |A X
                |A Y
                |B Z
                |C Z
                |A Z
                |B X
                |B Z
                |C Z
                |C Z
                |B Z
                |C X
                |B Z
                |C Z
                |A X
                |B Z
                |A X
                |B Z
                |B Z
                |C X
                |A Y
                |C Z
                |C Z
                |A X
                |B Y
                |C Z
                |B X
                |C Z
                |B Z
                |A Z
                |A X
                |A X
                |A Z
                |A X
                |A X
                |C Z
                |C Z
                |C Z
                |C Z
                |B Z
                |A Y
                |B Z
                |B Z
                |C Z
                |B Z
                |C Z
                |C Z
                |B Z
                |B X
                |A Y
                |C Z
                |C Z
                |B Z
                |B Z
                |C Z
                |B Z
                |B Z
                |C Z
                |C Z
                |A Z
                |C Z
                |B Z
                |B Z
                |C Z
                |C Z
                |C Y
                |C Z
                |A Y
                |B Y
                |C Z
                |A X
                |B Z
                |C Z
                |A Y
                |B Z
                |B Z
                |B Z
                |C Z
                |C Z
                |A X
                |A X
                |C Z
                |C X
                |B Z
                |C X
                |A Z
                |C Z
                |B Z
                |C Z
                |C Z
                |C X
                |B Z
                |C Z
                |B Z
                |C Z
                |A X
                |C X
                |C Z
                |C Z
                |B Z
                |C Z
                |C Z
                |B Z
                |B Z
                |A X
                |C Z
                |C Z
                |B Z
                |A X
                |A X
                |C Z
                |A Y
                |B Z
                |C Z
                |C Z
                |C Z
                |B X
                |C Z
                |C Y
                |B Z
                |B Z
                |C Y
                |A X
                |A Y
                |C Z
                |A Z
                |B Z
                |A X
                |B Z
                |C Y
                |B Z
                |C Z
                |B Z
                |B Z
                |B Z
                |A X
                |C Z
                |B Z
                |C Z
                |C Z
                |C Y
                |C Z
                |A Y
                |C Z
                |C Y
                |A Z
                |B Z
                |C Z
                |A X
                |B Z
                |B Z
                |C Z
                |C X
                |A X
                |C Z
                |A Z
                |A X
                |C Z
                |A Z
                |C Z
                |B Z
                |A Z
                |C Z
                |B Z
                |B Z
                |B X
                |B Z
                |C Z
                |A X
                |C Z
                |B Z
                |B Z
                |A X
                |B Z
                |C Z
                |B Y
                |A X
                |A Z
                |C Z
                |B Y
                |A Z
                |A Y
                |C X
                |B Z
                |B Z
                |C X
                |C Y
                |A X
                |A Y
                |C Z
                |A X
                |A Z
                |B Z
                |B Z
                |A X
                |A X
                |C Z
                |A X
                |C X
                |A X
                |C Z
                |A X
                |B Z
                |C Z
                |B Z
                |B Z
                |A X
                |C Z
                |B Z
                |B Z
                |B Z
                |A X
                |C Z
                |A X
                |B Z
                |C X
                |B Z
                |A Z
                |A X
                |C X
                |C Y
                |B Z
                |C Z
                |C X
                |B Z
                |A X
                |C Z
                |B Z
                |A X
                |B Z
                |A Z
                |C Z
                |B Z
                |C X
                |B Z
                |C Z
                |A Z
                |A X
                |A X
                |A Y
                |A X
                |C Z
                |B Z
                |C Z
                |A X
                |C Z
                |C Z
                |B Z
                |C Z
                |C Z
                |C Z
                |C Z
                |C Z
                |C Z
                |B Z
                |B Z
                |B Z
                |B Z
                |B Z
                |C Z
                |B Z
                |B X
                |C Z
                |B Y
                |B Z
                |C Y
                |A Z
                |B Z
                |A Z
                |B Z
                |C Z
                |C Z
                |C Z
                |B Z
                |A X
                |C Z
                |A X
                |B Y
                |C Z
                |C X
                |B Y
                |A X
                |C Z
                |C Z
                |A Y
                |A X
                |B Z
                |A Y
                |B Z
                |C Z
                |C Z
                |A X
                |B Z
                |B Z
                |C Y
                |C Z
                |B Z
                |C Z
                |B X
                |C Z
                |B Z
                |B X
                |A Y
                |A X
                |C Z
                |B Z
                |B Z
                |C Z
                |B Z
                |A Y
                |C Z
                |A Y
                |B Z
                |C Z
                |B Z
                |A Z
                |B Z
                |C Z
                |C Z
                |A Z
                |C Z
                |C X
                |A Y
                |A X
                |C Z
                |B Z
                |C Z
                |C Y
                |C Z
                |C Z
                |B Z
                |C Z
                |C Z
                |B Z
                |C X
                |B Y
                |C Z
                |B Z
                |A X
                |C Z
                |B Z
                |B Z
                |A Y
                |C Z
                |C Z
                |B X
                |B Z
                |C Z
                |A Z
                |C Z
                |A Z
                |C Z
                |C Z
                |B Z
                |C X
                |B Y
                |C Z
                |C Y
                |C Z
                |C Z
                |C Z
                |A X
                |A X
                |B Z
                |C Z
                |C Z
                |B Z
                |C Z
                |A X
                |C Z
                |C Y
                |A X
                |B Z
                |B Z
                |A X
                |A Y
                |B Z
                |B X
                |A X
                |C Z
                |C Z
                |B Z
                |A Z
                |B Z
                |B Z
                |C Y
                |A Y
                |B X
                |C Z
                |A Z
                |A Z
                |B Z
                |A Z
                |C Y
                |B Z
                |B Z
                |C Z
                |A X
                |C Z
                |C Z
                |B Z
                |B Z
                |C Z
                |C Z
                |C Z
                |A Y
                |B Z
                |C Z
                |A Z
                |C Z
                |A X
                |B Z
                |C Z
                |A Y
                |B Z
                |B Y
                |C Z
                |B Z
                |C Z
                |C X
                |A X
                |B Z
                |B Z
                |C Z
                |A X
                |A X
                |B Z
                |C Z
                |B Z
                |C Z
                |B X
                |B Z
                |B Z
                |B Z
                |C Z
                |B Z
                |B Z
                |C Z
                |A X
                |A X
                |C Z
                |B Y
                |A X
                |A Z
                |B Z
                |B Z
                |B Z
                |C X
                |B X
                |B Z
                |C Z
                |A X
                |A Z
                |B X
                |A Z
                |B Z
                |C Z
                |A Y
                |C Z
                |B Y
                |B Z
                |B Y
                |C Z
                |A Z
                |C Z
                |B Z
                |C Z
                |C Z
                |A X
                |A X
                |B Z
                |B Z
                |B X
                |B Y
                |A X
                |C Z
                |B Z
                |C Z
                |B X
                |C Z
                |B Z
                |C Y
                |C Z
                |B Z
                |A X
                |A Z
                |B Y
                |A X
                |B Z
                |A X
                |C Z
                |B Z
                |C Z
                |B Z
                |C Z
                |C Z
                |A X
                |C Z
                |B Z
                |B Z
                |A X
                |B Y
                |C Z
                |B Z
                |C X
                |B Z
                |C Z
                |B Z
                |B Z
                |B Z
                |C X
                |B X
                |C Z
                |A X
                |B Z
                |B Z
                |B Z
                |C X
                |B Z
                |C Z
                |B Z
                |A X
                |C Z
                |C Z
                |B X
                |C Y
                |C Z
                |B Z
                |B Y
                |C Z
                |B X
                |C Z
                |A Z
                |C Z
                |C Z
                |B Z
                |B Z
                |A Z
                |A X
                |B Z
                |C X
                |B Z
                |C Z
                |B Z
                |C Z
                |C Z
                |B Z
                |A X
                |B Z
                |C Z
                |C Z
                |C Z
                |C Z
                |A Y
                |B Z
                |B Z
                |C Z
                |B Z
                |C Z
                |C Z
                |B Z
                |A Y
                |C Z
                |C Z
                |C X
                |B Z
                |A X
                |B Z
                |C Z
                |C Z
                |C Y
                |B X
                |C Z
                |B X
                |B Z
                |B X
                |A X
                |A X
                |A Y
                |A Y
                |A Z
                |A Z
                |C Z
                |C Z
                |C Z
                |C Z
                |C Z
                |A X
                |A X
                |C X
                |B Z
                |B Z
                |C Z
                |C Z
                |A X
                |C Z
                |A X
                |B Z
                |C X
                |B Z
                |C Z
                |B Z
                |B Z
                |B Z
                |C Z
                |C Z
                |A X
                |A X
                |C Z
                |C Z
                |A X
                |A Y
                |B Z
                |A Z
                |A X
                |C Z
                |B Z
                |C Z
                |C Z
                |A X
                |A X
                |C Z
                |A X
                |B Z
                |C Z
                |C Z
                |A Z
                |C Z
                |C Z
                |A X
                |B Z
                |A X
                |B Z
                |C Z
                |B Z
                |C Z
                |C Y
                |A Z
                |A X
                |C Z
                |B Z
                |C X
                |A Z
                |B Z
                |B Z
                |C Z
                |A X
                |B Z
                |A X
                |C Z
                |B Z
                |B Z
                |B Z
                |B Z
                |A Z
                |B Z
                |B Z
                |C Z
                |A X
                |B Z
                |C Z
                |C Z
                |C Y
                |A X
                |A X
                |B Z
                |C Z
                |C Z
                |B Z
                |C Z
                |C Y
                |C Y
                |A X
                |C Z
                |C Z
                |A X
                |B Z
                |B Z
                |C Z
                |A Y
                |A Y
                |C Z
                |B Z
                |C X
                |B Z
                |B Z
                |C Z
                |A X
                |B Z
                |A X
                |C Z
                |C Z
                |A X
                |B Y
                |C Z
                |B X
                |C Z
                |C Z
                |B Z
                |A X
                |B Z
                |A Y
                |C Z
                |C X
                |A X
                |A Y
                |C Z
                |B Y
                |B Z
                |B Z
                |B Z
                |A Z
                |B Z
                |C Z
                |B Z
                |B X
                |B Z
                |C Z
                |B Z
                |C Z
                |B Z
                |A X
                |B Z
                |A Z
                |C Z
                |B X
                |A X
                |C Z
                |B Z
                |C Z
                |A Z
                |A X
                |B Z
                |B Z
                |B Z
                |B Z
                |C Z
                |B Z
                |C Z
                |B Z
                |B Z
                |B Z
                |B Z
                |C Z
                |C Z
                |C Y
                |A Y
                |C Z
                |C Z
                |B Z
                |B X
                |A X
                |C Z
                |A Y
                |C Y
                |C X
                |C Z
                |C Z
                |B Z
                |B Z
                |C X
                |A Z
                |B Z
                |C Z
                |C Z
                |A X
                |C X
                |B Z
                |B Z
                |A X
                |B X
                |B Z
                |C Z
                |B Z
                |C Z
                |C Y
                |B Z
                |B Z
                |B Z
                |C Z
                |A Z
                |C Z
                |C X
                |C Z
                |B Z
                |B Z
                |A Y
                |B Z
                |C X
                |C Z
                |A X
                |C Z
                |B Z
                |A X
                |C Z
                |A Y
                |B Z
                |B Z
                |A X
                |B Z
                |B Z
                |C Z
                |B Z
                |B Z
                |C Z
                |B X
                |B Z
                |B Z
                |A Y
                |C Z
                |B Z
                |C Z
                |B Y
                |C Z
                |A X
                |C X
                |A X
                |C Z
                |A Z
                |A Y
                |C Z
                |C Z
                |A Y
                |B Z
                |B X
                |C Z
                |A X
                |B Z
                |C Z
                |C Z
                |C Z
                |B Z
                |A Y
                |A Y
                |C X
                |B Y
                |C Z
                |B Z
                |A X
                |C Z
                |A Z
                |B Z
                |A X
                |B X
                |A Z
                |B Y
                |A Z
                |A Y
                |B Z
                |B Z
                |A Z
                |B Z
                |A Z
                |B Z
                |B Z
                |C Z
                |A Z
                |C Z
                |C Z
                |C Z
                |A Z
                |C Z
                |B Z
                |A X
                |B Z
                |A X
                |A X
                |B Z
                |B Z
                |C Z
                |B Z
                |A X
                |C X
                |B Z
                |C Z
                |C Z
                |C Y
                |C Z
                |C Z
                |B Z
                |B Z
                |C Z
                |B Y
                |A X
                |C Z
                |C Z
                |C Z
                |C Z
                |C Z
                |C Z
                |B Z
                |B Z
                |C Z
                |C Z
                |A X
                |C Z
                |C Z
                |A X
                |B Z
                |B Z
                |C Z
                |B Z
                |C Z
                |B Z
                |B Z
                |B Z
                |B Z
                |C Z
                |C Z""".stripMargin
      )
    )

}
