package io.dohrm.adventOfCode2022

object D3 {
  def getPriority(c: Char): Int =
    if (c <= 'z' && c >= 'a') c.toInt + 1 - 'a'.toInt
    else if (c <= 'Z' && c >= 'A') c.toInt + 1 - 'A'.toInt + 26
    else 0
  final case class Rucksack(first: Array[(Char, Int)], second: Array[(Char, Int)]) {
    lazy val allItems: Array[(Char, Int)]  = (first ++ second).sortBy(_._1)
    lazy val findItem: Option[(Char, Int)] = first.find(v => second.exists(_._1 == v._1))
  }

  def rucksack(list: String): Rucksack = Rucksack(
    list.substring(0, list.length / 2).toCharArray.map(c => c -> getPriority(c)).sortBy(_._1),
    list.substring(list.length / 2).toCharArray.map(c => c -> getPriority(c)).sortBy(_._1)
  )

  def part1(items: List[Rucksack]): Unit =
    println(items.flatMap(_.findItem.toList).map(_._2).sum)

  def part2(items: List[Rucksack]): Unit = {
    println(
      items
        .grouped(3)
        .flatMap { items =>
          items
            .flatMap(v => v.allItems.distinct)
            .groupBy(v => v)
            .find(_._2.size >= 3)
            .map(_._1._2)
            .toList
        }
        .sum
    )
  }
  def run(fn: List[Rucksack] => Unit, value: String): Unit =
    fn(
      value.split("\n").map(_.trim).map(rucksack).toList
    )

  def main(args: Array[String]): Unit =
    run(
      part2,
      """GbccTtTSGGbgrcWBGGrdgTnVQnCmNpCJlNnNPVfClcnN
        |vMzvZhzhwDLVmQnClwwNQp
        |FRsZFzjQFsqRzRRjDZbdtTgdHBBWGrdBdHHs
        |HCLTmbCLgzNBNPSSlT
        |JJGMWRJMrrdwWWGjGWMLRGLjBzNQsBzPPfflzDPBsBffDrQz
        |pwJdLMjdMddWjLtwZWMMwGtHhnvnCnhvqVFFZnvbgbqVCZ
        |tvMCDCSVVvDDBQFRbqWMMsWgFWgc
        |BLLPTpBmfLPrHLLfLsbhRqbzRRcRHgqssR
        |dfdNLmPTdNZmZdZPfpmTJLPPSvQjtSGVwQSDJSjSwDQBVCGw
        |wZWTWNFqzwZbWNpSgGMVMtTHsgGs
        |nlnPnPvLQjzdtsjBHBMMGSHg
        |LdnrrLnhRdLLmLDRPvmdQnJDJWNqcCqZJZqfFqfcfzcq
        |vPTbfWggzvGVqjsVqV
        |dDcJHZcZHmMFQQMshsjcRqVChjNtqh
        |dDHJDmFnrJmQFnBdMdQHJdZZlWTTPPjTLWbTzLWlTTfwjzBT
        |VfmDHDfZzfLcZLLLHBFQtRJTcdjgdTgFjjtR
        |WRPhMlGSshPRGgvFMtddTjjCQt
        |SPhWPsbNWShsWllswGpzLmzfZwmZfqLVRrDBZB
        |MtZgRgJJbbGjgDDgbjRjRbGcNdWwncBFdLBBMhFBQwnWnw
        |vlpsNVsCzzfHpvTpzlSSSvppcQdfnwnWhndWndwfQLhnhcFQ
        |pCsCCTHVvSzvPvHvzpPVTVHHRJJDgJZjJjqNmjZmDtJRZPNR
        |GTGTbhhPjJJjBhhZsGzmfHSNsmHHgSdL
        |FcFpMDFDRFfsRHSjmLjR
        |CpFjqcCjwjnpwhTPTWBQZZTb
        |zdzzwDlnTDQQQQnqQqqsFqnrSBSprbpjNJJBJPPdpJfbZb
        |hgMcRVGMtHgRcNSPrpfgfjJpBp
        |CLRHVHhtvtvGPWFFDqPDLnqP
        |jssjjjHCSGCMNJTWWCJT
        |DvcvBtVrrDSNWcMfLRfM
        |ppDZSpBhBvBmvDHnFsHHPnGPGbQp
        |VVVLsLWnjVVBGgScjtBjjLLgmJdPmJmfmhmGmmmNmJGhPNJP
        |QbqlZqQTZvMHmshvFhPfffFp
        |CsTRrQrwbCbrZqQTQlRjtDBSBtwBjgVWLBtgBt
        |FLsSFRTPscHZmGRGGc
        |npNNptgttCNpgLbnQMgnQnMNqVhGqZrmrmmqrmcrqmCVZwqH
        |WMWbtpjLgnLNvSfPPzjvjPdv
        |FcFFhZlhlMrHlSFSrHZMJZSVmmLmVLLCsBtLBCzCBVDRcV
        |PMGPbndvGfGstLzDCmLB
        |NwjPqdvPpvgddqgwHrZhJlTlThpWJMZp
        |SdjStScTWTwwvwwfjRhQPQQQDlLBGpLrPrLrLc
        |gCqJbNsVsNMgzMJnnqzNlCLGGlZZPrLLlLLtpPDl
        |JsFJFMmbJqqnJbhSHdjWwjtmHWvS
        |zBFDGGbNzDWRbDccsWslHlWWsJcS
        |zMVqTwzPfVfVMwmlcZTZZlSmTlmc
        |MrMvMCnrMVMCPrPnDFFGgQdFgRdzznbd
        |rJtJnrnSShJgcCsjjNNMSSDzRmzm
        |HWDWPBPDBfFVBffqplvlmNlQllvzQNQqlN
        |FVGHHFVbwBpBPwFFGfBpHVDgrcJCbZcLdCgtcCcJLJrd
        |MGHGGFFqbFTGmFwLmQsQflFN
        |WcvBdpjhdZdNwdZwLZ
        |vWtgVcpvjthtNcjntDhhpSJMSqHzqTzqCVHTSqHPGT
        |cVHZfjfZMcrSDQMJRCBCQw
        |PtGddtslsWQDBdwCDDdw
        |WsvTFnshPTGhGhhlPNGTCnsjgFVfmgfHZfVHgcHZVVFmFV
        |JFFqfJBgrHBffVHlsBFqfWNgjTtztNnttWWvWNwzwt
        |hGZbcBcZZSQmZLQRTbvNttTzjtTvbpzv
        |cmmhRchPZhZSSmdmGPDDdJdBVMffHlqlslfF
        |qWwTNwNHMHNNMRqMdRMQQMHLmmvzrTmrzPvzJvZvZlvzjZ
        |FphBpnBhVBSFvLljzZPpmrPL
        |nGsBbssbcbdlwggdNl
        |RLSRTLSFFFLPSWpzzTJdzsQpbd
        |DvqqcwVMDDcfrrnwDcwnvCdpQQphJhJjhdhpzsJhMQ
        |fGcvDZffcGGZDHGrGrtJRPlPmJSlPLRgNBHg
        |QlFFmGQFDQrrWlRlWGrnQVCLNvvPwLCwBvCcCcJCLCCm
        |tHtfsjSMCNPwzvCf
        |MjqStqMHsMSgjShjTttgphsTlrbDWGDrGlRTlNDbQrQRWRbD
        |QbChcCJCbHQCjbGCjQfsdsrtTqrfTLrcFftd
        |DwRzVzzZnzZRwvgRhRWtqsLLWtRdqLLdqd
        |NMwMzBVVPPSGQhBl
        |ttTPHWdrJjCdjnFMtLLtLNvQltLh
        |pSDBwZRBBsgfDGGsGpBVMFPQQlFMFQQFQfNvLNfF
        |PsppZzBVzwgDwBwwgpSSBssWjqrdCnjjHdmCTHznWCJJWn
        |WcdHdPcdZrLPDPBQDg
        |pMjMMqfmJlqNflMlFNRfLBwnLzTTTDJJwDTTGTLJ
        |hlhbqpbNNbVVdbZtSB
        |RDBWGRDnzBWBJDNBttSLlclldtQQcTTLFF
        |rTPVjZZsCZrVhdFMcgLgwFSgQh
        |PsjHVffbsTCHrCvTPfDJGJHNzzNJWnnnmzDB
        |LQdFgTLdQjVsQFTRBjMZrmBjWGMGSW
        |flvJJlJpbNnppCpMGGfBBZSZRfFmGr
        |NNbNDNlbDpHlbDDplvzvnCbzqsQPFQsTTccsqdQqLgdHLwQw
        |DnGDNDTFdFwDzCZZRmhThCRRRv
        |SgrPLrrLsBPbHBCmtVZVCdCcctHH
        |rSbgBrsqgsPppMBqfpPsLpPGlNGGDwNFNJWDldlllDwJMG
        |PWbvNWvpvJPnWDGqDjDczj
        |QwfFFVVQSMlDlQfFZhsHrBrhHHTcjnczqjzqrG
        |mwMSgfmDmSSFgfFNbmLpbRbJbvbRpC
        |lsggLLLDGldGTGBBhNTCwRwVnJnNCCnbRV
        |QQpWrpHtrHrpNRRJNtfbJCVR
        |PvQQFPzccvBglclNscls
        |NsszMMNGWLcWBhMF
        |gTtwvbqfnDTdpvqDftpnnntDZvLFQFBLmRWFRhJZJhLLBRQB
        |DwrpDbngprPWGllSNrSS
        |nCqdLPZPMMZLNvtGhRmGhGPmtW
        |TSrVZVSZVwFTgSVtrtchvWRRrtWtcr
        |gjbjBjgTjfgfVfHHppBLMnqLMDnqClsZJLLD
        |hrqShCPCpHHBVBGWQFVQGFGnzQDf
        |tgvZsbwsbcMbRsgccjDGFvGFfWJLLzFFQJ
        |TTZmMcgmbmWZMctbbtsHrrqqSHHrCrPBBSCPrT
        |HHHNZLGLpBpRSvWlGlqhPghqDGnnFr
        |QCNCMTJdjMjdjsQTbdQmmCQDngFqnggPFcPcnPFcDqcbDn
        |MNJfzNsfJdJjdzwMNjjTJttSHVStRtZVwHvWRWtZHt
        |DSbvDdDbbwHgCSgZPwpbPgmTTJhsTTChqTJssQssFmJJ
        |zzjMNNGMMRcNNhvnvFqmtJJv
        |WWffvlVrcGzGlcjLvfrVRLHgHgpDPSbPpwwHbWbBbPPH
        |FCCjjFlFtCjzlpTHtJsQTTcpTT
        |DWLhWSgDWWdSWLwmmpHHQTHcBTBvvwHvHl
        |mgGRhrLLgWqnjrfCNlzP
        |cLsslBlsqNNTHlTVNbLZZLRCQbZZdQdpbP
        |JGfJhhwfwBBSJPRdZddpZRQbfR
        |hWmWGgDhJrFhBcWsssWHvHll
        |lmmvlJFtMHFtQzVSRbPGzLJRgG
        |BcTcrNBrrwwqDBqNqwcrhLpLPVzRhPRPPPgSGVPLbS
        |TrDqcnsTcsmnvHtdGtMW
        |CcnDQpSDcnFcPBrmbPQGBsGB
        |gCtCfRZTBWbjPRbr
        |qgvHqgJhMfZTtvHgfTghJgMJDpdppFSLLCcSDvLLcdDwvLcw
        |ffFgGRMWSTGcnDgllDDpDp
        |dvSdHBrVSLNVLjdlsllcsDqpsZ
        |SHHHNrLJLvtNQJVvmMfGRGGRCJWJRwzWMh
        |JNpNDfDBDHVzwHHzpzBWVBPsvsFNCbmbqsFFNsjCmvsmNC
        |rnnrtLhnrrQZMvtFbWmqtllcFb
        |GQRdGQLLhMSQhZLZdgdwwHzPDzSVWzVDwJDVpz
        |LdcGjgdcrMDSFGVfnnGG
        |HNsCCQFCPvFFBJnnSBJVfDVJwf
        |HHFRqHPpNppmQPcpLjzrdgtbgztT
        |GlZZbclGZsDvlGhsShRnCnMQtjtQjnCQsQRM
        |PggFVcdFNFNNVVFLPdPdrwpWBMMnqMpnttJMnjMnQqtqQtqq
        |FdgcdcLwfTmSGTmhlbzG
        |RGvhGrLhhRhlpChZrGSprBdPPHJJSBgSSHqBWBBffH
        |mQmjmwtTMTVLzHnTPWffPHHJBf
        |jMmmwMcVcFLFrlRshZbCrF
        |SnNgNgBlNZSZdZtMrlnSnnQtjpwFwpvFJwFqpwSbqjjqGRpv
        |CLCcWHLhLTzsDPcCWMLGpFJbGFwsbvGwJwjpRv
        |zMCTPhmHWzfhQQmndNllNrQg
        |dbdBdZrQsrdrGslrrSpLvwHmlTmmwScTHv
        |FgnJqLDLWqNnNpppmpCSSmCJTw
        |NNhhnRNfzMhgnMDFfGdGLbBVVdQRtPVZGt
        |BBQJNTTzTcfRhtjhffqDDWCC
        |vZnsLsVLSvPwPFFnwPlSPgZWqGjChgWCCWWCMCgGMh
        |srLLnLmlPwrrPwmwwvlRqzQRJBmppQTTQpTdBN
        |PLDpZGpWbNGWLDfQmsQDwwsmhm
        |vTzMMbgCfgHQsmQt
        |VMlRznlzVnTcFzbMcrpJcNrJdjdpZrLdcZ
        |SftvFcDSvDHsFtctMSvbdjbpqpRRpRTJrMdrrb
        |QzQZWZnQgQZwBBwsJdqPjdjrnTpJjs
        |NGmwmgszhZwwGGgZGmggWLVSVHlNVVtDcDltFVVVlVHt
        |WCfFBfBHHjHHjgHBjJFVcVRwQMbVrRhrJbRRJM
        |sZMsDqzZPRrRrVswdc
        |vvTzDzpDTvpDvZPvSnNZZlSHMCHjjFtWmlttlCjmCF
        |hJZwhrvhBJRrPQPwRRZLllgLqfcqpTggpcTWMTff
        |HHDzMztbVgTzNpgf
        |nGbmtjDMFjDjCHbbbHHHdBQQPBrZvJQRwvwRPZQJGs
        |NNSrMSHRqWpWNNrNMvLffTBBDmsvcmcJLM
        |lwPPhcddcGPlBDTDlmDvJJsv
        |bZhzCdPGGFzVVPwVwbNtcqHrpnpZptSZqRrt
        |GvvSWhmhWBNcBDNc
        |FzlRRTljjRTjRRmZfbflRTlFFrrMrcBcDVqBVsNDDJsMFr
        |bttRfzfRHzjlmlnCbTtzbRShgwHGGvppLdpvwLLGLLhd
        |MHGMWdBFFNsFFHpWSFddMmqVmVBggmlVfbVffjgZml
        |hcJsTTscvsLDzDJmqVgfqbqnbmfJbJ
        |PvRTzsPwLcwCprSdwdNW
        |qfJnJdLpJzrcqCrCzcGfpRSSVBPRSjSSllTNRBdTRS
        |DbsbtggsbbsghhgvnWWSlVjPSjmmPBtjPNlTmS
        |vHHHHDHvZHQvWbWsZDgWhDwWzpfGfzfcpFJzczwFJrfffnGC
        |sQvsRQsFZvfpGhjhQqjpZvjGJHgngPBNHnCBJBCmSBmBNG
        |HTHwbtdTDDnCTPTT
        |zwMlVdzbzLzMWvQZRQZfZZlHsR
        |QhzWwRBPHgFrWWrH
        |SDgJCCDCsVpMMqTtFpfpqG
        |gJNCCddSZNSlljQzPPNBzR
        |dLzVVjfLGCCdRPrdmBtwWttr
        |NnbNsbTHJnbHbSHlNQsNtwrJRwBMMBhrPJWZRRtM
        |QSslpFvpSSsQPFCDqqgzcjCj
        |fcpGshsfNcNZsmRjNqCtnFgbCgHrrggmrn
        |QvzBlBBQBdJTBzBwVVMgbrwwLFtLtgLFHCHrbF
        |dlQQMBSSTPZfPcfssZNC
        |gNGVMzVpVVTdPDWdRdNT
        |BfjbnCBjBzffHrbrzBDddQWTZZQTTJTQTHHS
        |zrFncfBjcjnrrlCLwFgpmvFmwGmVLh
        |MbngccTfWgbWcTTzZghmLshhLRttpthRDLtf
        |CdFdJHCJjBvBSCNCNJBjjdjpsPDwDtwvptRPmLmzRwhhLR
        |qJSCCBFHQBFFldrVZZbggnGTzcZQ
        |lPrpppllcwwpHprppNdfLbQJnWdLJnncdN
        |tSjjjSSDGgghRbbSTfTbTFTLQn
        |jCBgDMbBMGghZzCZmmlrrpwp
        |FhCDFvvPwCjcLhDjhnvjnsdfZTlflQlflLsppdQfld
        |zPNSmmHrSSHWBNSMMVGzfGfZTZQZzdpdRGZR
        |WSNVVMMVtHSVbMNWBHqmwcvhcgwgvwtPvgtPDjtw
        |jSSSjzZMmgSzzwmZBtHcHmtNdncHtnpNcn
        |VsLsRsJJsTfRVfLRLJlfLlWqNbDcddncvpvbdvcnpqdpdtHq
        |GQQTsJGGJLlRGJFWffWLhgZwrZBZFZrhtBjrjjZw
        |ZfzJPvPnLvRJRfZLDfjfrBcqrgsgDBrcrGgslsms
        |SNhpqSNhpVTNQSMNgWmrlccVGBBmwrBw
        |QHHFhhNdTNHHfZPFqtqPRtjq
        |PMZSPSZZGMspsLhLRqRVzfGjvF
        |tcwwgcgbcbCrtbbtmQQcCqRffFLhRgqjFjRfhFqhqz
        |CLQtcbcmwmbdrbBrlrCwQTsTPsPsZNBPNWJpZWpTss
        |lMTrcHrhChWnRzJrznnr
        |DDJbPwjLJpfBQjPVBpbsGVGVWnZnsqnZsnzsqZ
        |wJQLbpPJDLfgPbDNCHNlghNCMhcNcl
        |tlVZhlVWtnBltVtssZBBbPbcpdPwbPWfvcbLvbbb
        |NwCTFNFDNdSNPpLpfN
        |CGwRjwDjzFFGRGjjFRjlBtZqMzVVtVqhMZMBZn
        |HhFdMFHhgrdjcZtZjr
        |zvvQQvzwzDMjZTjtcrTDtt
        |BwMwSvQSVlzQlMQzwzNgGHPGGHFCCCgGhsHLCS
        |zMVtBhhVhhDhtzBtMTTfDrPbmRRmPbQmrQbNQGRQtR
        |vLlJHgnLpDvHHvHvmPbSQbQRGmJmPRrb
        |pspwHClCwqplsHqDsMMTFWsWfjzszf
        |CmmjLwWSWGCHCjwSmStJBgQcccBhwgQtgthQ
        |WZVFTpqWsMsZpFddzszbVzJQBnRtrQthchdBgtgRtdrc
        |bbsMTWsMVsZqNZMpqWDqbMsCjvlCfjGCPlLLPLCmSCfCLN
        |VzsjjVGhpjJrJHCppprt
        |WtMnqtWdSQDtMRSnLNHHwHwQvrJrJCPN
        |tTtWSScTddBqdRMmlsbFBfhVBhfjjF
        |gLMWzdTgLFQHdlMgMRwcwhqqvPcPhVFRDF
        |tBnGrSCZNZCrtGBsSNGtBPhcgfchqqDPwVPRvNRqwN
        |CmrgstjZngtBzbjJlQWWHjjM
        |qttwGWHtVPzJJPqbmb
        |NrRvfTTghNrpLrrpLTrNrRrhvJmzmzlbbVVbdbdZlDdvzMPb
        |rfcprNcfgpLrVNnnCcnnscstFGCF
        |ZZhTfggZsbshGrfshMrNMCSRMMWqCqMNRq
        |TVTJPDTFccqMCcJw
        |BBLBmLTLDHFvsQpfgnZhbQvG
        |ffSrFvVVmVCQSfVDFzDvDDmmnGWCRqGRWNNqlttnRsNtGnWW
        |PgZQgPJJpTpTHRGtNRGWqZMWWR
        |wdTdwgbPJTJgTgLSFBbrQvSrFrVS
        |ppssshsscCVCHhVWVpznnQRBnZnBbzczFPRS
        |dqqfJGWttfWGlwwPSbFbZnRFPFtFZS
        |wGwdGdddLfGgMTJfwLMlJMpTCChjHhjTHpjjhmsDHmHW
        |PZQBhRPQBQrWHFHqHFHCqh
        |STQSvvvppzSVHJJFWjHC
        |TTgTvbsbszcNnnvbncvRGPBRtRgQrDPLfftPPR
        |dMltttpQhmQVZdmhsdrvNCHvlWbHWvHCWrlr
        |PzzLTGpGPDzFBzqFGFqFvHWHvRJbbrbWvCvjJCLv
        |BpqTBzpzfGGTTPZtSddtQmVffSst
        |bwHbRZldhQQfDWWGDjBf
        |CzvgpsNMsvCvFvpszpnMsFgBTDBDWPnPVJJZZDJnfjDTff
        |CpcLsFrMZbhRcdmt
        |HgjpWlhzpWjhWTQPFdPBRQzTMQ
        |JsfwrqLttwJVLGhRQGGPBd
        |CttfrqDmDDtCsbZCHjhZHSHNlgcW
        |QSdCWlCRhWRdlrlZrDssZsGDbv
        |pjPrpjqFNrZNGnBbsNDG
        |wjjVHjfLQRCgdLrC
        |PjMpRdBdjMSGsjpdprqtwCrNGrrNlthhrG
        |WQzDzLZDgzZcqlqqrtJclJnh
        |zbWHQHDfDWZHfLZHfffWVZpRSPpdVvBSPMqVMPjdvspS
        |TMBJLTJlFHBjFFtMGngpvvpgvQmtNSNngv
        |bVhsZswRCbbVZWVfVZwVSpmSQPPvNHwPHmgmSSNN
        |dCCVZZcbWVVcCbbfsLrdjFMJdDDHBTMrjr
        |vNWcTWnCqNCPPjhhHsQrfgszrTJRQsfRQD
        |wLdwMBLFBBQJpszJBqzB
        |lLwVmMSmttVMlSNqcbcbSbNcvHbh
        |PVfJfDWrPVPPLcPPFWcjPrqlqqQsljRpplqBQpRvSQvs
        |NdggMTCChMgdChNmdtTbtmsQSRhQslhlpFRpFwllwQvw
        |CdnGzbGbgMGMdTCZZDDJcZFDDnWrPH
        |fsshhnfLZSvcVbdcZVJj
        |RCCSmDFFpRqHQDgWvbGjgjDdbG
        |pFmFtCSBCSMBBLwrPsBPNlNB
        |fWWcwbbwbWfGCPgPfvbwgvgcQQqQLsGLJQTZHHrZRsrLqlJs
        |VnszmsDBpMFpzNFlrlRLRRHZqRHr
        |VpdzDMNzNDjpsdzdnzDcPCwtWCjhbthvfgtgwP
        |SPQtSWDLLltQQctHLSBSWHlWgFwhMRsgwggrFJPgdgwwGJhJ
        |nCqmfVqfVjTznCMhsGRRRgGFMffw
        |mCnNTVzVvjmqNtlDtbttDlBM
        |LjctjtppFWmgthgs
        |nBrNvzTqlDJlbbZgvmhMZVZb
        |JJrnTrrgGDqDPwwSPHPpfjRdPc
        |sTQmCmmVqmJHSTjGdMMfMNNvNHvc
        |rFbzlLLWWPzwlWrlbwzrWbRvdfFjdjpvjfFNNMccphCvhN
        |rrWzrwzPBBBCZTJgZg
        |gffvjftWddzZtbvdNvgZLwBBMJLSWMDMDDBRWRmS
        |PqPqpqcCnCpVqlClTQQmPMDwPRJJBLLLhS
        |VCGqlHmmHsjtHNsZ
        |mmMlVllWmhmmBzzLGMWlBmpstptPRRZpPMFJSpRsFRFs
        |DgjnndQcNTCCCDNcdSRSdtZPfwfwJSJJ
        |gQjCQqQjHNnjDCgHNcZGZLhHzrLVLGzlrGmb
        |JfwfJpBgJSMphZqtqDDG
        |QcQrssrGCcMCVcMc
        |RnljPRnPjWbGRbjnjbvmSzwHfHgwfJHzdLFSwBFW
        |sBjbHCBCnjvsJCHBsbvwwJGfRNFFFfFGTcrVFffNHRTP
        |zDqdpqMgMtgzthgDtQmzGPTVSTVrVGTFSVFFqNRF
        |zDLdphmmLhMhDhQdlzgLLbjCnWswWWlrZJBswCJJZl
        |FMNrQFgrVwmrpJMwMTMPflbsHPTtlSbftSjCbC
        |zGnGnhnGzDqRLnZLHNHbbbHDlltNSjCl
        |nzddcRzzBnRRvRRhvnQFpmpgggJVcVmMQmgN
        |CCpMlhwwpJpdBlsdcjvtZDFrtmRqmDrsmv
        |gzVPbjSPfSPTTTPnWVSbbvDQZZDZrFWDvFDvmvQQmZ
        |LTbLTPgnTzLVPNNGnNTgVNPlGdHHCphMwHMwjMphlpjccl
        |rMMrqcrmJqJqmCsTPWWGGPzPlPPrGL
        |fnwqwwZwRnVlWWnzWBWlDP
        |jvVHvqfpJmhtHJtH
        |NLMVQjRNTJCTJtZTJc
        |DlGlGHvFHGDgcFCtfhCJFtZc
        |DBHGGGSDvGDPHWBGdBbSvgWDNVMjLLRnmNmjPLNPNcRQVnjj
        |tsGdTJdJtNllzjGRzm
        |HZvvDLLWqbBBMRMRNjVhHRmn
        |vZDCvqqgBDZZjbZDrWqBvpdpFpcdpCJcPTSJJtptpP""".stripMargin
    )

}
